### ISSUE TITLE
Sensible version strings

### ISSUE THREAD

**Issue by wozman** [jenkinsci/jjwt-api-plugin#6]
Can we have version strings in line with the majority of other plugins, i.e major.minor.patch please?
We have an automated process to pull plugins to an internal on-prem repo and 0.11.2.8.82737cbfa6f5 has broken the version parser.

**Comment by jglick** [comment]
Fix your parser? https://jenkins.io/jep/229

**Comment by wozman** [comment]
It's not my parser, it's a vendor product. Never mind, helpful as ever.

**Comment by jglick** [comment]
What vendor would this be? For some “repository”?

https://github.com/jenkinsci/lib-version-number/blob/6069936f093629bcf6e3a559dd67bb20a583d056/src/main/java/hudson/util/VersionNumber.java#L36-L53 FTR. There is no limit on the number of version number components, and nonnumeric final components are permitted. Also compliant with Maven (modulo https://github.com/jenkinsci/lib-version-number/pull/6).

**Comment by wozman** [comment]
Yes understood. Unfortunately I work for a very large corporate and I'm not permitted to divulge any details. I'll raise it with the internal repo support team.
